services:
  - type: web
    name: ebamage-api
    env: php
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
